name: CI

on: [push]

jobs:
  build-0.60.0-vnext:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: npm install
      run: npm install
      working-directory: 0.60.0-vnext
    - name: react-native run-windows --info
      run: npm run react-native -- run-windows --info
      working-directory: 0.60.0-vnext

  build-minimal-app-beta:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: npm install
      run: npm install
      working-directory: minimal-app-beta
    - name: react-native run-windows --info
      run: npm run react-native -- run-windows --info
      working-directory: minimal-app-beta
