name: CI

on: [push]

jobs:
  build-0_60_0-vnext:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: microsoft/setup-msbuild@v1.0.0
    - name: npm install
      run: npm install
      working-directory: 0.60.0-vnext
    - name: react-native run-windows --info
      run: npm run react-native -- run-windows --info
      working-directory: 0.60.0-vnext
    - name: react-native run-windows --no-deploy --no-launch
      run: npm run react-native -- run-windows --no-deploy --no-launch
      working-directory: 0.60.0-vnext

  build-0_61_0-beta:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: microsoft/setup-msbuild@v1.0.0
    - name: npm install
      run: npm install
      working-directory: 0.61.0-beta
    - name: react-native run-windows --info
      run: npm run react-native -- run-windows --info
      working-directory: 0.61.0-beta
    - name: react-native run-windows --no-deploy --no-launch
      run: npm run react-native -- run-windows --no-deploy --no-launch
      working-directory: 0.61.0-beta

  build-0_61_2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: microsoft/setup-msbuild@v1.0.0
    - name: npm install
      run: npm install
      working-directory: 0.61.2
    - name: react-native run-windows --info
      run: npm run react-native -- run-windows --info
      working-directory: 0.61.2
    - name: react-native run-windows --no-deploy --no-launch
      run: npm run react-native -- run-windows --no-deploy --no-launch
      working-directory: 0.61.2

  build-0_60_0-with-dnd:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: microsoft/setup-msbuild@v1.0.0
    - name: npm install
      run: npm install
      working-directory: 0.60.0-with-dnd
    - name: react-native run-windows --info
      run: npm run react-native -- run-windows --info
      working-directory: 0.60.0-with-dnd
    - name: react-native run-windows --no-deploy --no-launch
      run: npm run react-native -- run-windows --no-deploy --no-launch
      working-directory: 0.60.0-with-dnd

  build-0_61_2-with-dnd:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: microsoft/setup-msbuild@v1.0.0
    - name: npm install
      run: npm install
      working-directory: 0.61.2-with-dnd
    - name: react-native run-windows --info
      run: npm run react-native -- run-windows --info
      working-directory: 0.61.2-with-dnd
    - name: react-native run-windows --no-deploy --no-launch
      run: npm run react-native -- run-windows --no-deploy --no-launch
      working-directory: 0.61.2-with-dnd

  build-0_61_2-with-dnd2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: microsoft/setup-msbuild@v1.0.0
    - name: npm install
      run: npm install
      working-directory: 0.61.2-with-dnd2
    - name: react-native run-windows --info
      run: npm run react-native -- run-windows --info
      working-directory: 0.61.2-with-dnd2
    - name: react-native run-windows --no-deploy --no-launch
      run: npm run react-native -- run-windows --no-deploy --no-launch
      working-directory: 0.61.2-with-dnd2

  build-0_61_2-with-dnd3:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: microsoft/setup-msbuild@v1.0.0
    - name: npm install
      run: npm install
      working-directory: 0.61.2-with-dnd3
    - name: react-native run-windows --info
      run: npm run react-native -- run-windows --info
      working-directory: 0.61.2-with-dnd3
    - name: react-native run-windows --no-deploy --no-launch
      run: npm run react-native -- run-windows --no-deploy --no-launch
      working-directory: 0.61.2-with-dnd3

  build-0_61_2-with-webview:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: microsoft/setup-msbuild@v1.0.0
    - name: npm install
      run: npm install
      working-directory: 0.61.2-with-webview
    - name: react-native run-windows --info
      run: npm run react-native -- run-windows --info
      working-directory: 0.61.2-with-webview
    - name: react-native run-windows --no-deploy --no-launch
      run: npm run react-native -- run-windows --no-deploy --no-launch
      working-directory: 0.61.2-with-webview

  build-0_61_9:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: microsoft/setup-msbuild@v1.0.0
    - name: npm install
      run: npm install
      working-directory: 0.61.9
    - name: react-native run-windows --info
      run: npm run react-native -- run-windows --info
      working-directory: 0.61.9
    - name: react-native run-windows --no-deploy --no-launch
      run: npm run react-native -- run-windows --no-deploy --no-launch
      working-directory: 0.61.9

  build-0_61_9-with-fs:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: microsoft/setup-msbuild@v1.0.0
    - name: npm install
      run: npm install
      working-directory: 0.61.9-with-fs
    - name: react-native run-windows --info
      run: npm run react-native -- run-windows --info
      working-directory: 0.61.9-with-fs
    - name: react-native run-windows --no-deploy --no-launch
      run: npm run react-native -- run-windows --no-deploy --no-launch
      working-directory: 0.61.9-with-fs

  build-0_61_9-with-fs2:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - uses: microsoft/setup-msbuild@v1.0.0
    - name: npm install
      run: npm install
      working-directory: 0.61.9-with-fs2
    - name: react-native run-windows --info
      run: npm run react-native -- run-windows --info
      working-directory: 0.61.9-with-fs2
    - name: react-native run-windows --no-deploy --no-launch
      run: npm run react-native -- run-windows --no-deploy --no-launch
      working-directory: 0.61.9-with-fs2
